sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"
addons:
  apt:
    packages:
      - hunspell
      - libhunspell-dev
# command to install dependencies
install:
  - pip install .
# command to run tests
# TODO add some basic tests
#script: nosetests
